//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace farm.el_porvenir
{

    [Persistent(@"cliente")]
    public partial class Cliente : XPLiteObject
    {
        int fId_cliente;
        [Key(true)]
        [Persistent(@"id_cliente")]
        public int Id_cliente
        {
            get { return fId_cliente; }
            set { SetPropertyValue<int>(nameof(Id_cliente), ref fId_cliente, value); }
        }
        string fNombre;
        [Size(45)]
        [Persistent(@"nombre")]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fApellido;
        [Size(45)]
        [Persistent(@"apellido")]
        public string Apellido
        {
            get { return fApellido; }
            set { SetPropertyValue<string>(nameof(Apellido), ref fApellido, value); }
        }
        int fTelefono;
        [Persistent(@"telefono")]
        public int Telefono
        {
            get { return fTelefono; }
            set { SetPropertyValue<int>(nameof(Telefono), ref fTelefono, value); }
        }
        string fDireccion;
        [Size(45)]
        [Persistent(@"direccion")]
        public string Direccion
        {
            get { return fDireccion; }
            set { SetPropertyValue<string>(nameof(Direccion), ref fDireccion, value); }
        }
        [Association(@"FacturaReferencesCliente")]
        public XPCollection<Factura> Facturas { get { return GetCollection<Factura>(nameof(Facturas)); } }
    }

}
