//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace farm.el_porvenir
{

    [Persistent(@"detallefactura")]
    public partial class Detallefactura : XPLiteObject
    {
        int fId_detalleFactura;
        [Key(true)]
        [Persistent(@"id_detalleFactura")]
        public int Id_detalleFactura
        {
            get { return fId_detalleFactura; }
            set { SetPropertyValue<int>(nameof(Id_detalleFactura), ref fId_detalleFactura, value); }
        }
        int fCantidad;
        [Persistent(@"cantidad")]
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        double fPrecioVenta;
        [Persistent(@"precioVenta")]
        public double PrecioVenta
        {
            get { return fPrecioVenta; }
            set { SetPropertyValue<double>(nameof(PrecioVenta), ref fPrecioVenta, value); }
        }
        double fIVA;
        public double IVA
        {
            get { return fIVA; }
            set { SetPropertyValue<double>(nameof(IVA), ref fIVA, value); }
        }
        double fSubTotal;
        [Persistent(@"subTotal")]
        public double SubTotal
        {
            get { return fSubTotal; }
            set { SetPropertyValue<double>(nameof(SubTotal), ref fSubTotal, value); }
        }
        int fFactura;
        public int Factura
        {
            get { return fFactura; }
            set { SetPropertyValue<int>(nameof(Factura), ref fFactura, value); }
        }
        int fMedicamento;
        public int Medicamento
        {
            get { return fMedicamento; }
            set { SetPropertyValue<int>(nameof(Medicamento), ref fMedicamento, value); }
        }
    }

}
