//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace farm.el_porvenir
{

    [Persistent(@"empleado")]
    public partial class Empleado : XPLiteObject
    {
        int fId_empleado;
        [Key(true)]
        [Persistent(@"id_empleado")]
        public int Id_empleado
        {
            get { return fId_empleado; }
            set { SetPropertyValue<int>(nameof(Id_empleado), ref fId_empleado, value); }
        }
        string fNombre;
        [Size(45)]
        [Persistent(@"nombre")]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fCargo;
        [Size(45)]
        [Persistent(@"cargo")]
        public string Cargo
        {
            get { return fCargo; }
            set { SetPropertyValue<string>(nameof(Cargo), ref fCargo, value); }
        }
        string fSalario;
        [Size(45)]
        [Persistent(@"salario")]
        public string Salario
        {
            get { return fSalario; }
            set { SetPropertyValue<string>(nameof(Salario), ref fSalario, value); }
        }
        [Association(@"FacturaReferencesEmpleado")]
        public XPCollection<Factura> Facturas { get { return GetCollection<Factura>(nameof(Facturas)); } }
    }

}
