//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace farm.el_porvenir
{

    [Persistent(@"factura")]
    public partial class Factura : XPLiteObject
    {
        int fId_factura;
        [Key(true)]
        [Persistent(@"id_factura")]
        public int Id_factura
        {
            get { return fId_factura; }
            set { SetPropertyValue<int>(nameof(Id_factura), ref fId_factura, value); }
        }
        string fId_empleado;
        [Size(45)]
        [Persistent(@"id_empleado")]
        public string Id_empleado
        {
            get { return fId_empleado; }
            set { SetPropertyValue<string>(nameof(Id_empleado), ref fId_empleado, value); }
        }
        string fFecha;
        [Size(45)]
        [Persistent(@"fecha")]
        public string Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<string>(nameof(Fecha), ref fFecha, value); }
        }
        int fN_factura;
        [Persistent(@"n_factura")]
        public int N_factura
        {
            get { return fN_factura; }
            set { SetPropertyValue<int>(nameof(N_factura), ref fN_factura, value); }
        }
        string fId_cliente;
        [Size(45)]
        [Persistent(@"id_cliente")]
        public string Id_cliente
        {
            get { return fId_cliente; }
            set { SetPropertyValue<string>(nameof(Id_cliente), ref fId_cliente, value); }
        }
        decimal fVenta_total;
        [Persistent(@"venta_total")]
        public decimal Venta_total
        {
            get { return fVenta_total; }
            set { SetPropertyValue<decimal>(nameof(Venta_total), ref fVenta_total, value); }
        }
        Empleado fEmpleado_id_empleado;
        [Persistent(@"empleado_id_empleado")]
        [Association(@"FacturaReferencesEmpleado")]
        public Empleado Empleado_id_empleado
        {
            get { return fEmpleado_id_empleado; }
            set { SetPropertyValue<Empleado>(nameof(Empleado_id_empleado), ref fEmpleado_id_empleado, value); }
        }
        Cliente fCliente_id_cliente;
        [Persistent(@"cliente_id_cliente")]
        [Association(@"FacturaReferencesCliente")]
        public Cliente Cliente_id_cliente
        {
            get { return fCliente_id_cliente; }
            set { SetPropertyValue<Cliente>(nameof(Cliente_id_cliente), ref fCliente_id_cliente, value); }
        }
        int fMedicamento_id_med;
        [Indexed(Name = @"fk_factura_medicamento1_idx")]
        [Persistent(@"medicamento_id_med")]
        public int Medicamento_id_med
        {
            get { return fMedicamento_id_med; }
            set { SetPropertyValue<int>(nameof(Medicamento_id_med), ref fMedicamento_id_med, value); }
        }
    }

}
