//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace farm.el_porvenir
{

    [Persistent(@"inventario")]
    public partial class Inventario : XPLiteObject
    {
        int fId_inventario;
        [Key(true)]
        [Persistent(@"id_inventario")]
        public int Id_inventario
        {
            get { return fId_inventario; }
            set { SetPropertyValue<int>(nameof(Id_inventario), ref fId_inventario, value); }
        }
        string fFecha_compra;
        [Size(45)]
        [Persistent(@"fecha_compra")]
        public string Fecha_compra
        {
            get { return fFecha_compra; }
            set { SetPropertyValue<string>(nameof(Fecha_compra), ref fFecha_compra, value); }
        }
        int fTotal_compra;
        [Persistent(@"total_compra")]
        public int Total_compra
        {
            get { return fTotal_compra; }
            set { SetPropertyValue<int>(nameof(Total_compra), ref fTotal_compra, value); }
        }
        string fId_proveedor;
        [Size(45)]
        [Persistent(@"id_proveedor")]
        public string Id_proveedor
        {
            get { return fId_proveedor; }
            set { SetPropertyValue<string>(nameof(Id_proveedor), ref fId_proveedor, value); }
        }
        int fMedicamento_id_med;
        [Indexed(Name = @"fk_inventario_medicamento1_idx")]
        [Persistent(@"medicamento_id_med")]
        public int Medicamento_id_med
        {
            get { return fMedicamento_id_med; }
            set { SetPropertyValue<int>(nameof(Medicamento_id_med), ref fMedicamento_id_med, value); }
        }
        Proveedor fProveedor_id_proveedor;
        [Persistent(@"proveedor_id_proveedor")]
        [Association(@"InventarioReferencesProveedor")]
        public Proveedor Proveedor_id_proveedor
        {
            get { return fProveedor_id_proveedor; }
            set { SetPropertyValue<Proveedor>(nameof(Proveedor_id_proveedor), ref fProveedor_id_proveedor, value); }
        }
        int fStock;
        [Persistent(@"stock")]
        public int Stock
        {
            get { return fStock; }
            set { SetPropertyValue<int>(nameof(Stock), ref fStock, value); }
        }
        int fMedicamento;
        public int Medicamento
        {
            get { return fMedicamento; }
            set { SetPropertyValue<int>(nameof(Medicamento), ref fMedicamento, value); }
        }
    }

}
