//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace farm.el_porvenir
{

    [Persistent(@"laboratorios")]
    public partial class Laboratorios : XPLiteObject
    {
        int fId_laboratorios;
        [Key(true)]
        [Persistent(@"id_laboratorios")]
        public int Id_laboratorios
        {
            get { return fId_laboratorios; }
            set { SetPropertyValue<int>(nameof(Id_laboratorios), ref fId_laboratorios, value); }
        }
        string fDirecion;
        [Size(45)]
        [Persistent(@"direcion")]
        public string Direcion
        {
            get { return fDirecion; }
            set { SetPropertyValue<string>(nameof(Direcion), ref fDirecion, value); }
        }
        Proveedor fProveedor_id_proveedor;
        [Persistent(@"proveedor_id_proveedor")]
        [Association(@"LaboratoriosReferencesProveedor")]
        public Proveedor Proveedor_id_proveedor
        {
            get { return fProveedor_id_proveedor; }
            set { SetPropertyValue<Proveedor>(nameof(Proveedor_id_proveedor), ref fProveedor_id_proveedor, value); }
        }
    }

}
