//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace farm.el_porvenir
{

    [Persistent(@"medicamento")]
    public partial class Medicamento : XPLiteObject
    {
        string fNombre;
        [Size(45)]
        [Persistent(@"nombre")]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fCategoria;
        [Size(45)]
        [Persistent(@"categoria")]
        public string Categoria
        {
            get { return fCategoria; }
            set { SetPropertyValue<string>(nameof(Categoria), ref fCategoria, value); }
        }
        float fPrecio;
        [Persistent(@"precio")]
        public float Precio
        {
            get { return fPrecio; }
            set { SetPropertyValue<float>(nameof(Precio), ref fPrecio, value); }
        }
        string fStock;
        [Size(45)]
        [Persistent(@"stock")]
        public string Stock
        {
            get { return fStock; }
            set { SetPropertyValue<string>(nameof(Stock), ref fStock, value); }
        }
        int fFactura_id_factura;
        [Persistent(@"factura_id_factura")]
        public int Factura_id_factura
        {
            get { return fFactura_id_factura; }
            set { SetPropertyValue<int>(nameof(Factura_id_factura), ref fFactura_id_factura, value); }
        }
        DateTime fFecha_vencimiento;
        [Persistent(@"fecha_vencimiento")]
        public DateTime Fecha_vencimiento
        {
            get { return fFecha_vencimiento; }
            set { SetPropertyValue<DateTime>(nameof(Fecha_vencimiento), ref fFecha_vencimiento, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("id_med")]
            public int Id_med { get; set; }
            [Persistent("laboratorios_id_laboratorios")]
            public int Laboratorios_id_laboratorios { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
