//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace farm.el_porvenir
{

    [Persistent(@"proveedor")]
    public partial class Proveedor : XPLiteObject
    {
        int fId_proveedor;
        [Key(true)]
        [Persistent(@"id_proveedor")]
        public int Id_proveedor
        {
            get { return fId_proveedor; }
            set { SetPropertyValue<int>(nameof(Id_proveedor), ref fId_proveedor, value); }
        }
        string fNombre;
        [Size(45)]
        [Persistent(@"nombre")]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fLaboratorio;
        [Size(45)]
        [Persistent(@"laboratorio")]
        public string Laboratorio
        {
            get { return fLaboratorio; }
            set { SetPropertyValue<string>(nameof(Laboratorio), ref fLaboratorio, value); }
        }
        int fTelefono;
        [Persistent(@"telefono")]
        public int Telefono
        {
            get { return fTelefono; }
            set { SetPropertyValue<int>(nameof(Telefono), ref fTelefono, value); }
        }
        string fDireccion;
        [Size(45)]
        [Persistent(@"direccion")]
        public string Direccion
        {
            get { return fDireccion; }
            set { SetPropertyValue<string>(nameof(Direccion), ref fDireccion, value); }
        }
        string fProveedorcol;
        [Size(45)]
        [Persistent(@"proveedorcol")]
        public string Proveedorcol
        {
            get { return fProveedorcol; }
            set { SetPropertyValue<string>(nameof(Proveedorcol), ref fProveedorcol, value); }
        }
        [Association(@"InventarioReferencesProveedor")]
        public XPCollection<Inventario> Inventarios { get { return GetCollection<Inventario>(nameof(Inventarios)); } }
        [Association(@"LaboratoriosReferencesProveedor")]
        public XPCollection<Laboratorios> LaboratoriosCollection { get { return GetCollection<Laboratorios>(nameof(LaboratoriosCollection)); } }
    }

}
